server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/usuarios/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false